---
kind: pipeline
type: docker
name: coding-standard-php7.0

platform:
  os: linux
  arch: amd64

workspace:
  base: /var/www/owncloud
  path: server/apps/user_external

steps:
- name: coding-standard
  pull: always
  image: owncloudci/php:7.0
  commands:
  - make test-php-style

trigger:
  ref:
  - refs/pull/**
  - refs/tags/**
  - refs/heads/master

---
kind: pipeline
type: docker
name: phpstan-php7.2

platform:
  os: linux
  arch: amd64

workspace:
  base: /var/www/owncloud
  path: server/apps/user_external

steps:
- name: install-core
  pull: always
  image: owncloudci/core
  settings:
    core_path: /var/www/owncloud/server
    db_host: sqlite
    db_name: owncloud
    db_password: owncloud
    db_type: sqlite
    db_username: owncloud
    exclude: apps/user_external
    version: daily-master-qa

- name: setup-server-user_external
  pull: always
  image: owncloudci/php:7.2
  commands:
  - cd /var/www/owncloud/server
  - php occ a:l
  - php occ a:e user_external
  - php occ a:e testing
  - php occ a:l
  - php occ config:system:set trusted_domains 1 --value=server
  - php occ log:manage --level 2

- name: phpstan
  pull: always
  image: owncloudci/php:7.2
  commands:
  - make test-php-phpstan

trigger:
  ref:
  - refs/pull/**
  - refs/tags/**
  - refs/heads/master

---
kind: pipeline
type: docker
name: phan-php7.0

platform:
  os: linux
  arch: amd64

workspace:
  base: /var/www/owncloud
  path: server/apps/user_external

steps:
- name: install-core
  pull: always
  image: owncloudci/core
  settings:
    core_path: /var/www/owncloud/server
    db_host: sqlite
    db_name: owncloud
    db_password: owncloud
    db_type: sqlite
    db_username: owncloud
    exclude: apps/user_external
    version: daily-master-qa

- name: phan
  pull: always
  image: owncloudci/php:7.0
  commands:
  - make test-php-phan

trigger:
  ref:
  - refs/pull/**
  - refs/tags/**
  - refs/heads/master

---
kind: pipeline
type: docker
name: phan-php7.1

platform:
  os: linux
  arch: amd64

workspace:
  base: /var/www/owncloud
  path: server/apps/user_external

steps:
- name: install-core
  pull: always
  image: owncloudci/core
  settings:
    core_path: /var/www/owncloud/server
    db_host: sqlite
    db_name: owncloud
    db_password: owncloud
    db_type: sqlite
    db_username: owncloud
    exclude: apps/user_external
    version: daily-master-qa

- name: phan
  pull: always
  image: owncloudci/php:7.1
  commands:
  - make test-php-phan

trigger:
  ref:
  - refs/pull/**
  - refs/tags/**
  - refs/heads/master

---
kind: pipeline
type: docker
name: phan-php7.2

platform:
  os: linux
  arch: amd64

workspace:
  base: /var/www/owncloud
  path: server/apps/user_external

steps:
- name: install-core
  pull: always
  image: owncloudci/core
  settings:
    core_path: /var/www/owncloud/server
    db_host: sqlite
    db_name: owncloud
    db_password: owncloud
    db_type: sqlite
    db_username: owncloud
    exclude: apps/user_external
    version: daily-master-qa

- name: phan
  pull: always
  image: owncloudci/php:7.2
  commands:
  - make test-php-phan

trigger:
  ref:
  - refs/pull/**
  - refs/tags/**
  - refs/heads/master

---
kind: pipeline
type: docker
name: phan-php7.3

platform:
  os: linux
  arch: amd64

workspace:
  base: /var/www/owncloud
  path: server/apps/user_external

steps:
- name: install-core
  pull: always
  image: owncloudci/core
  settings:
    core_path: /var/www/owncloud/server
    db_host: sqlite
    db_name: owncloud
    db_password: owncloud
    db_type: sqlite
    db_username: owncloud
    exclude: apps/user_external
    version: daily-master-qa

- name: phan
  pull: always
  image: owncloudci/php:7.3
  commands:
  - make test-php-phan

trigger:
  ref:
  - refs/pull/**
  - refs/tags/**
  - refs/heads/master

---
kind: pipeline
type: docker
name: chat-notifications

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
- name: notify-rocketchat
  pull: always
  image: plugins/slack:1
  settings:
    channel: builds
    webhook:
      from_secret: private_rocketchat

trigger:
  ref:
  - refs/tags/**
  - refs/heads/master
  status:
  - success
  - failure

...
